export interface Anime {
  id: number
  title: string
  poster: string
  trailer: string
  telegramLink: string
  genre: string
  year: string
  rating: string
  language: string
  description: string
  views: number
}

export const animes: Anime[] = [
  {
    id: 1,
    title: "Spirited Away",
    poster: "/a1id.jpg",
    trailer: "https://www.youtube.com/embed/aL-97TEa43Y?si",
    telegramLink: "https://t.me/animeversebd/9",
    genre: "Action | Drama | Thriller",
    year: "2001",
    rating: "9.1",
    language: "Hindi",
    description: "A magical journey to a spirit world beyond imagination.",
    views: 1250
  },
{
  id: 2,
  title: "The Monkey King",
  poster: "/a2id.jpg",
  trailer: "https://www.youtube.com/embed/0pmIANSKkdo?si",
  telegramLink: "https://t.me/animeverse_bd",
  genre: "Action | Supernatural | Historical",
  year: "2023",
  rating: "5.6",
  language: "Hindi",
  description: "এক কিংবদন্তীর শুরু, এক অসাধারণ অভিযান।",
  views: 2340
},
{
  id: 3,
  title: "Your Name",
  poster: "/a3id.jpg",
  trailer: "https://www.youtube.com/embed/_oWzYOwXn-o?si",
  telegramLink: "https://t.me/animeversebd/13",
  genre: "Action | School | Supernatural",
  year: "2016",
  rating: "8.4",
  language: "Hindi",
  description: "দুই হৃদয়ের অলৌকিক গল্প, যা সময় ও দূরত্বকে ছাপিয়ে যায়।",
  views: 3450
},
{
  id: 4,
  title: "A Whisker Away",
  poster: "/a4id.jpg",
  trailer: "https://www.youtube.com/embed/zGGp2RVoPdU?si",
  telegramLink: "https://t.me/animeversebd/17",
  genre: "Adventure | Comedy | Action",
  year: "2020",
  rating: "6.7",
  language: "Hindi",
  description: "A magical adventure with unexpected twists.",
  views: 1890
},
{
  id: 5,
  title: "Drifting Home",
  poster: "/a5id.jpg",
  trailer: "https://www.youtube.com/embed/zY5O9JRPKLY?si",
  telegramLink: "https://t.me/animeversebd/19",
  genre: "Action | Martial Arts | Adventure",
  year: "2022",
  rating: "6.5",
  language: "Hindi",
  description: "A heartwarming story of friendship and adventure.",
  views: 1567
},
{
  id: 6,
  title: "Once Upon a Witch's Death Season 1",
  poster: "/a6id.jpg",
  trailer: "https://www.youtube.com/embed/FerOCv5eOHI?si",
  telegramLink: "https://t.me/animeversebd/21",
  genre: "Action | Adventure | Martial Arts",
  year: "2025",
  rating: "8.7",
  language: "Hindi",
  description: "A thrilling tale of magic and mystery.",
  views: 2100
},
{
  id: 7,
  title: "A Great Cleric Season 1",
  poster: "/a7id.jpg",
  trailer: "https://www.youtube.com/embed/susqUMviH_E?si",
  telegramLink: "https://t.me/animeversebd/46",
  genre: "Superhero | School | Action",
  year: "2023",
  rating: "7.5",
  language: "Hindi",
  description: "An epic journey of a powerful cleric.",
  views: 1750
},
{
  id: 8,
  title: "Rurouni Kenshin Season 1",
  poster: "/a8id.jpg",
  trailer: "https://www.youtube.com/embed/ZONOltoCdP4?si",
  telegramLink: "https://t.me/animeversebd/73",
  genre: "Thriller | Supernatural | Psychological",
  year: "2023",
  rating: "7.9",
  language: "Hindi",
  description: "A legendary swordsman's journey through time.",
  views: 1900
},
{
  id: 9,
  title: "A Couple of Cuckoos Season 1",
  poster: "/a9id.jpg",
  trailer: "https://www.youtube.com/embed/WtBwfWvUEqY?si",
  telegramLink: "https://t.me/animeversebd/82",
  genre: "Comedy | Action | Supernatural",
  year: "2022",
  rating: "7.1",
  language: "Hindi",
  description: "A hilarious romantic comedy with supernatural elements.",
  views: 1600
},
{
  id: 10,
  title: "The Misfit of Demon King Academy Season 1",
  poster: "/a10id.jpg",
  trailer: "https://www.youtube.com/embed/e8YBesRKq_U?si",
  telegramLink: "https://t.me/animeversebd/137",
  genre: "Action | Supernatural | Adventure",
  year: "2020",
  rating: "7.3",
  language: "Hindi",
  description: "A powerful demon king returns to his academy.",
  views: 1800
},
{
  id: 11,
  title: "Shangri La Frontier Season 2",
  poster: "/a11id.jpg",
  trailer: "https://www.youtube.com/embed/R_7Okd4X1lU?si",
  telegramLink: "https://t.me/animeversebd/193",
  genre: "Action | Adventure | Fantasy | Game",
  year: "2025",
  rating: "8.6",
  language: "Hindi",
  description: "An epic gaming adventure continues.",
  views: 2200
},
{
  id: 12,
  title: "Attack on Titan Season 1",
  poster: "/a12id.jpg",
  trailer: "https://www.youtube.com/embed/LajOXSdyBeE?si",
  telegramLink: "https://t.me/animeversebd/198",
  genre: "Action | Supernatural | Adventure",
  year: "2013",
  rating: "9.0",
  language: "Hindi",
  description: "Humanity fights for survival against giant titans.",
  views: 2500
},
{
  id: 13,
  title: "Attack on Titan Season 2",
  poster: "/a13id.jpg",
  trailer: "https://www.youtube.com/embed/X2WGyFRKb8Y?si",
  telegramLink: "https://t.me/animeversebd/250",
  genre: "Action | Supernatural | Adventure",
  year: "2017",
  rating: "8.9",
  language: "Hindi",
  description: "The battle against titans intensifies.",
  views: 2400
},
{
  id: 14,
  title: "Attack on Titan Season 3",
  poster: "/a14id.jpg",
  trailer: "https://www.youtube.com/embed/mBGyz4G60cQ?si",
  telegramLink: "https://t.me/animeversebd/273",
  genre: "Action | Supernatural | Adventure",
  year: "2018",
  rating: "9.2",
  language: "Hindi",
  description: "Secrets of the titans are revealed.",
  views: 2600
},
{
  id: 15,
  title: "Attack on Titan Season 4",
  poster: "/a15id.jpg",
  trailer: "https://www.youtube.com/embed/cR0zTG2czV0?si",
  telegramLink: "https://t.me/animeversebd/318",
  genre: "Action | Supernatural | Adventure",
  year: "2020",
  rating: "9.3",
  language: "Hindi",
  description: "The final season brings epic conclusions.",
  views: 2700
},
{
  id: 16,
  title: "Olaf Presents Season 1",
  poster: "/a16id.jpg",
  trailer: "https://www.youtube.com/embed/2Stzk2aopxs?si",
  telegramLink: "https://t.me/animeversebd/376",
  genre: "Animation | Comedy | Short",
  year: "2021",
  rating: "7.3",
  language: "English",
  description: "Olaf presents hilarious Disney stories.",
  views: 1700
},
{
  id: 17,
  title: "Brave",
  poster: "/a17id.jpg",
  trailer: "https://www.youtube.com/embed/fyP0IGEzr4s?si",
  telegramLink: "https://t.me/animeversebd/389",
  genre: "Animation | Adventure | Fantasy",
  year: "2012",
  rating: "7.1",
  language: "English",
  description: "A brave princess fights for her destiny.",
  views: 1650
},
{
  id: 18,
  title: "DC League of Super-Pets",
  poster: "/a18id.jpg",
  trailer: "https://www.youtube.com/embed/dgtFO6ANznY?si",
  telegramLink: "https://t.me/animeversebd/391",
  genre: "Animation | Action | Comedy",
  year: "2022",
  rating: "7.2",
  language: "English/Hindi",
  description: "Superhero pets save the day.",
  views: 1750
},
{
  id: 19,
  title: "Doraemon: Nobita's Chronicle of the Moon Exploration",
  poster: "/a19id.jpg",
  trailer: "https://www.youtube.com/embed/w7Iz-zsltjw?si",
  telegramLink: "https://t.me/animeversebd/393",
  genre: "Animation | Sci-Fi | Adventure",
  year: "2019",
  rating: "6.7",
  language: "Hindi",
  description: "Doraemon and Nobita explore the moon.",
  views: 1550
},
{
  id: 20,
  title: "Justice Society: World War II",
  poster: "/a20id.jpg",
  trailer: "https://www.youtube.com/embed/qx2zoSk42BI?si",
  telegramLink: "https://t.me/animeversebd/395",
  genre: "Animation | Action | Superhero",
  year: "2021",
  rating: "6.4",
  language: "Hindi",
  description: "Superheroes fight in World War II.",
  views: 1450
},
{
  id: 21,
  title: "Puss in Boots: The Last Wish",
  poster: "/a21id.jpg",
  trailer: "https://www.youtube.com/embed/tsTLlZ32SpI?si",
  telegramLink: "https://t.me/animeversebd/397",
  genre: "Animation | Adventure | Comedy",
  year: "2022",
  rating: "7.8",
  language: "Hindi",
  description: "Puss in Boots goes on one last adventure.",
  views: 1850
},
{
  id: 22,
  title: "Constantine: City of Demons",
  poster: "/a22id.jpg",
  trailer: "https://www.youtube.com/embed/6vL--ZrHC6U?si",
  telegramLink: "https://t.me/animeversebd/399",
  genre: "Animation | Action | Fantasy",
  year: "2018",
  rating: "7.4",
  language: "English/Hindi",
  description: "Constantine battles demons in the city.",
  views: 1750
},
{
  id: 23,
  title: "Doraemon: Nobita and the Kingdom of Clouds",
  poster: "/a23id.jpg",
  trailer: "https://www.youtube.com/embed/6ndjhJo2zFw?si",
  telegramLink: "https://t.me/animeversebd/401",
  genre: "Animation | Adventure | Family",
  year: "1992",
  rating: "7.0",
  language: "Hindi",
  description: "Doraemon and friends discover a cloud kingdom.",
  views: 1600
},
{
  id: 24,
  title: "Hotel Transylvania 2",
  poster: "/a24id.jpg",
  trailer: "https://www.youtube.com/embed/E3mL9H3C2OY?si",
  telegramLink: "https://t.me/animeversebd/403",
  genre: "Animation | Comedy | Family",
  year: "2015",
  rating: "6.6",
  language: "English/Hindi",
  description: "Dracula's family returns for more fun.",
  views: 1500
},
{
  id: 25,
  title: "Hotel Transylvania 3: Summer Vacation",
  poster: "/a25id.jpg",
  trailer: "https://www.youtube.com/embed/Qvt0KnhtPBk?si",
  telegramLink: "https://t.me/animeversebd/405",
  genre: "Animation | Comedy | Family",
  year: "2018",
  rating: "6.3",
  language: "Hindi",
  description: "Dracula goes on a summer vacation.",
  views: 1400
},
{
  id: 26,
  title: "Ainbo: Spirit of the Amazon",
  poster: "/a26id.jpg",
  trailer: "https://www.youtube.com/embed/PWRtf3pc14c?si",
  telegramLink: "https://t.me/animeversebd/407",
  genre: "Animation | Adventure | Fantasy",
  year: "2021",
  rating: "4.8",
  language: "Hindi",
  description: "A girl protects the Amazon rainforest.",
  views: 1200
},
{
  id: 27,
  title: "Onward",
  poster: "/a27id.jpg",
  trailer: "https://www.youtube.com/embed/dLXt8r1cQVk?si",
  telegramLink: "https://t.me/animeversebd/409",
  genre: "Animation | Adventure | Comedy",
  year: "2020",
  rating: "7.4",
  language: "Hindi",
  description: "Two brothers go on a magical quest.",
  views: 1700
},
{
  id: 28,
  title: "Zootopia",
  poster: "/a28id.jpg",
  trailer: "https://www.youtube.com/embed/X4XvU9FT0NM?si",
  telegramLink: "https://t.me/animeversebd/411",
  genre: "Animation | Adventure | Comedy",
  year: "2016",
  rating: "8.0",
  language: "Hindi",
  description: "A rabbit cop and fox con artist solve crimes.",
  views: 1900
},
{
  id: 29,
  title: "Ben 10: Destroy All Aliens",
  poster: "/a29id.jpg",
  trailer: "https://www.youtube.com/embed/zIYZQpknKZQ?si",
  telegramLink: "https://t.me/animeversebd/414",
  genre: "Animation | Action | Sci-Fi",
  year: "2012",
  rating: "7.3",
  language: "Dual Audio",
  description: "Ben 10 fights to save the world.",
  views: 1700
},
{
  id: 30,
  title: "Shrek",
  poster: "/a30id.jpg",
  trailer: "https://www.youtube.com/embed/V2WydtFqZP8?si",
  telegramLink: "https://t.me/animeversebd/416",
  genre: "Animation | Comedy | Fantasy",
  year: "2001",
  rating: "7.1",
  language: "English/Hindi",
  description: "An ogre rescues a princess.",
  views: 1650
},
{
  id: 31,
  title: "Shrek 2",
  poster: "/a31id.jpg",
  trailer: "https://www.youtube.com/embed/YxXp4EB6-fQ?si",
  telegramLink: "https://t.me/animeversebd/418",
  genre: "Animation | Comedy | Adventure",
  year: "2004",
  rating: "7.2",
  language: "English",
  description: "Shrek meets his in-laws.",
  views: 1700
},
{
  id: 32,
  title: "The Jungle Book",
  poster: "/a32id.jpg",
  trailer: "https://www.youtube.com/embed/q6ZbvucX4Pg?si",
  telegramLink: "https://t.me/animeversebd/419",
  genre: "Animation | Adventure | Family",
  year: "1967",
  rating: "6.7",
  language: "Dual Audio",
  description: "A boy grows up in the jungle.",
  views: 1550
},
{
  id: 33,
  title: "The Secret Life of Pets 2",
  poster: "/a33id.jpg",
  trailer: "https://www.youtube.com/embed/Id9iHnlOZaI?si",
  telegramLink: "https://t.me/animeversebd/421",
  genre: "Animation | Comedy | Family",
  year: "2019",
  rating: "6.4",
  language: "English",
  description: "Pets go on new adventures.",
  views: 1450
},
{
  id: 34,
  title: "Turbo",
  poster: "/a34id.jpg",
  trailer: "https://www.youtube.com/embed/VlRtm8Gh9PQ?si",
  telegramLink: "https://t.me/animeversebd/423",
  genre: "Animation | Adventure | Comedy",
  year: "2013",
  rating: "7.8",
  language: "Dual Audio",
  description: "A snail dreams of racing.",
  views: 2890
},
{
  id: 35,
  title: "White Snake",
  poster: "/a35id.jpg",
  trailer: "https://www.youtube.com/embed/RYKRko-yaO4?si",
  telegramLink: "https://t.me/animeversebd/425",
  genre: "Animation | Fantasy | Romance",
  year: "2019",
  rating: "7.4",
  language: "Dual Audio",
  description: "A magical love story unfolds.",
  views: 1750
},
{
  id: 36,
  title: "Wonder Park",
  poster: "/a36id.jpg",
  trailer: "https://www.youtube.com/embed/kNIyjsmoKts?si",
  telegramLink: "https://t.me/animeversebd/427",
  genre: "Animation | Family | Fantasy",
  year: "2019",
  rating: "7.0",
  language: "English/Hindi",
  description: "A girl brings her imagination to life.",
  views: 1678
},
{
  id: 37,
  title: "Mojib Bai",
  poster: "/a37id.jpg",
  trailer: "https://www.youtube.com/embed/givLtqsybMo?si",
  telegramLink: "https://t.me/animeversebd/429",
  genre: "Animation | Adventure | Action",
  year: "2015",
  rating: "6.6",
  language: "Bangla",
  description: "A Bangladeshi animated adventure.",
  views: 1500
},
{
  id: 38,
  title: "Madan Senki Ryukendo",
  poster: "/a38id.jpg",
  trailer: "https://www.youtube.com/embed/vNgF_ZbVZHk?si",
  telegramLink: "https://t.me/animeversebd/431",
  genre: "Action | Fantasy | Tokusatsu",
  year: "2006",
  rating: "7.3",
  language: "Japanese/English",
  description: "A warrior fights for justice.",
  views: 1700
},
{
  id: 39,
  title: "What If... Season 1",
  poster: "/a39id.jpg",
  trailer: "https://www.youtube.com/embed/I7ztyv9dwgo?si",
  telegramLink: "https://t.me/animeversebd/536",
  genre: "Animation | Action | Sci-Fi",
  year: "2021",
  rating: "7.1",
  language: "English/Hindi",
  description: "Explore alternate Marvel universes.",
  views: 1650
},
{
  id: 40,
  title: "SK8 the Infinity Season 1",
  poster: "/a40id.jpg",
  trailer: "https://www.youtube.com/embed/cBPPj83KjTQ?si",
  telegramLink: "https://t.me/animeversebd/555",
  genre: "Sports | Action | Comedy",
  year: "2021",
  rating: "7.2",
  language: "Japanese/Hindi",
  description: "Underground skateboarding battles.",
  views: 1700
},
{
  id: 41,
  title: "Death Note Season 1",
  poster: "/a41id.jpg",
  trailer: "https://www.youtube.com/embed/R5JgNbmQBcY?si",
  telegramLink: "https://t.me/animeversebd/578",
  genre: "Mystery | Supernatural | Thriller",
  year: "2006",
  rating: "8.9",
  language: "Japanese/Hindi",
  description: "A notebook that can kill anyone.",
  views: 2400
},
{
  id: 42,
  title: "Roll No. 21 Season 1",
  poster: "/a42id.jpg",
  trailer: "https://www.youtube.com/embed/Zx4Yu2cujqI?si",
  telegramLink: "https://t.me/animeversebd/585",
  genre: "Animation | Comedy | Adventure",
  year: "2010",
  rating: "8.1",
  language: "Hindi",
  description: "A student's hilarious adventures.",
  views: 2000
},
{
  id: 43,
  title: "Roll No. 21 Season 2",
  poster: "/a43id.jpg",
  trailer: "https://www.youtube.com/embed/LTeXi8LgTy4?si",
  telegramLink: "https://t.me/animeversebd/632",
  genre: "Animation | Comedy | Adventure",
  year: "2013",
  rating: "7.8",
  language: "Dual Audio",
  description: "More adventures of Roll No. 21.",
  views: 1900
},
{
  id: 44,
  title: "Baki Hanma Season 2",
  poster: "/a44id.jpg",
  trailer: "https://www.youtube.com/embed/KN98VzNwjOY?si",
  telegramLink: "https://t.me/animeversebd/685",
  genre: "Action | Martial Arts | Anime",
  year: "2023",
  rating: "7.4",
  language: "Japanese/Hindi",
  description: "Intense martial arts battles.",
  views: 1750
},
{
  id: 45,
  title: "Blue Eye Samurai Season 1",
  poster: "/a45id.jpg",
  trailer: "https://www.youtube.com/embed/WfzXxTq_W6k?si",
  telegramLink: "https://t.me/animeversebd/738",
  genre: "Animation | Action | Drama",
  year: "2023",
  rating: "7.0",
  language: "Hindi/Japanese",
  description: "A samurai's quest for revenge.",
  views: 4567
},
{
  id: 46,
  title: "Puss in Boots",
  poster: "/a46id.jpg",
  trailer: "https://www.youtube.com/embed/tsTLlZ32SpI?si",
  telegramLink: "https://t.me/animeversebd/755",
  genre: "Animation | Comedy | Adventure",
  year: "2011",
  rating: "6.6",
  language: "English/Hindi",
  description: "The origin story of Puss in Boots.",
  views: 2234
},
{
  id: 47,
  title: "Invincible Season 1",
  poster: "/a47id.jpg",
  trailer: "https://www.youtube.com/embed/qR2xlrQiHDk?si",
  telegramLink: "https://t.me/animeversebd/757",
  genre: "Animation | Action | Superhero",
  year: "2021",
  rating: "6.6",
  language: "English/Hindi",
  description: "A young superhero's journey begins.",
  views: 1500
},
{
  id: 48,
  title: "Invincible Season 2",
  poster: "/a48id.jpg",
  trailer: "https://www.youtube.com/embed/13ahG2dEiWQ?si",
  telegramLink: "https://t.me/animeversebd/776",
  genre: "Animation | Action | Superhero",
  year: "2023",
  rating: "6.6",
  language: "English/Hindi",
  description: "Invincible faces greater challenges.",
  views: 1500
},
{
  id: 49,
  title: "Onimusha Season 1",
  poster: "/a49id.jpg",
  trailer: "https://www.youtube.com/embed/SqWxZEvMrdo?si",
  telegramLink: "https://t.me/animeversebd/779",
  genre: "Animation | Action | Samurai",
  year: "2023",
  rating: "6.6",
  language: "Japanese/Hindi",
  description: "A samurai fights supernatural forces.",
  views: 1500
},
{
  id: 50,
  title: "Tokyo Revengers Season 2",
  poster: "/a50id.jpg",
  trailer: "https://www.youtube.com/embed/eNZSurcYTW8?si",
  telegramLink: "https://t.me/animeversebd/797",
  genre: "Action | Drama | Supernatural",
  year: "2023",
  rating: "8.2",
  language: "Japanese/Hindi",
  description: "Time travel and gang warfare.",
  views: 2100
},
{
  id: 51,
  title: "Captain Laserhawk: A Blood Dragon Remix Season 1",
  poster: "/a51id.jpg",
  trailer: "https://www.youtube.com/embed/1cqWBOVszYo?si",
  telegramLink: "https://t.me/animeversebd/825",
  genre: "Animation | Action | Sci-Fi",
  year: "2023",
  rating: "7.9",
  language: "English",
  description: "A cyberpunk action adventure.",
  views: 1900
},
{
  id: 52,
  title: "Ultraman Season 3",
  poster: "/a52id.jpg",
  trailer: "https://www.youtube.com/embed/Tvb-9DWt45Q?si",
  telegramLink: "https://t.me/animeversebd/837",
  genre: "Action | Sci-Fi | Superhero",
  year: "2023",
  rating: "9.0",
  language: "Japanese/Hindi",
  description: "The ultimate superhero battles.",
  views: 2500
},
{
  id: 53,
  title: "Rurouni Kenshin Season 1 Ep 5-8",
  poster: "/a53id.jpg",
  trailer: "https://www.youtube.com/embed/ZONOltoCdP4?si",
  telegramLink: "https://t.me/animeversebd/862",
  genre: "Historical | Action | Romance",
  year: "2023",
  rating: "8.0",
  language: "Japanese/Hindi",
  description: "A legendary swordsman's tale.",
  views: 3789
},
{
  id: 54,
  title: "Rurouni Kenshin Season 1 Ep 13-19",
  poster: "/a54id.jpg",
  trailer: "https://www.youtube.com/embed/ZONOltoCdP4?si",
  telegramLink: "https://t.me/animeversebd/871",
  genre: "Historical | Action | Romance",
  year: "2023",
  rating: "9.0",
  language: "Japanese/Hindi",
  description: "Kenshin's journey continues.",
  views: 2500
},
{
  id: 55,
  title: "Justice League Season 1",
  poster: "/a55id.jpg",
  trailer: "https://www.youtube.com/embed/9Wly6N7dSkM?si",
  telegramLink: "https://t.me/animeversebd/886",
  genre: "Animation | Action | Superhero",
  year: "2001",
  rating: "9.2",
  language: "English/Hindi",
  description: "Earth's mightiest heroes unite.",
  views: 5678
},
{
  id: 56,
  title: "Baki Hanma Season 1",
  poster: "/a56id.jpg",
  trailer: "https://www.youtube.com/embed/pRYZRvYGMtc?si",
  telegramLink: "https://t.me/animeversebd/939",
  genre: "Action | Martial Arts | Anime",
  year: "2023",
  rating: "8.5",
  language: "Japanese/Hindi",
  description: "The strongest fighter emerges.",
  views: 2200
},
{
  id: 57,
  title: "Pokémon Ultimate Journeys Season 1",
  poster: "/a57id.jpg",
  trailer: "https://www.youtube.com/embed/wyrWFzV5U5Y?si",
  telegramLink: "https://t.me/animeversebd/964",
  genre: "Animation | Adventure | Fantasy",
  year: "2022",
  rating: "7.3",
  language: "Japanese",
  description: "Ash's ultimate Pokémon journey.",
  views: 1700
},
{
  id: 58,
  title: "Pokémon Ultimate Journeys Season 2",
  poster: "/a58id.jpg",
  trailer: "https://www.youtube.com/embed/sR1hzqn8k5w?si",
  telegramLink: "https://t.me/animeversebd/991",
  genre: "Animation | Adventure | Fantasy",
  year: "2023",
  rating: "9.0",
  language: "Japanese/Hindi",
  description: "The journey reaches new heights.",
  views: 2500
},
{
  id: 59,
  title: "Scott Pilgrim Takes Off Season 1",
  poster: "/a59id.jpg",
  trailer: "https://www.youtube.com/embed/WAqJZdsV3mo?si",
  telegramLink: "https://t.me/animeversebd/1024",
  genre: "Animation | Comedy | Romance | Action",
  year: "2023",
  rating: "8.6",
  language: "English/Hindi",
  description: "A fresh take on Scott Pilgrim.",
  views: 2200
},
{
  id: 60,
  title: "Ultraman Season 2",
  poster: "/a60id.jpg",
  trailer: "https://www.youtube.com/embed/AudT7Av-pv4?si",
  telegramLink: "https://t.me/animeversebd/1041",
  genre: "Action | Sci-Fi | Superhero",
  year: "2023",
  rating: "9.0",
  language: "Japanese/Hindi",
  description: "Ultraman returns stronger.",
  views: 2500
},
{
  id: 61,
  title: "Solo Leveling Season 1",
  poster: "/a61id.jpg",
  trailer: "https://www.youtube.com/embed/-tJMyIXjn9I?si",
  telegramLink: "https://t.me/animeversebd/1054",
  genre: "Action | Fantasy | Adventure",
  year: "2024",
  rating: "8.4",
  language: "Japanese/Hindi",
  description: "A hunter rises to power.",
  views: 2100
},
{
  id: 62,
  title: "Ultraman Season 1",
  poster: "/a62id.jpg",
  trailer: "https://www.youtube.com/embed/hLfNecWqzJs?si",
  telegramLink: "https://t.me/animeversebd/1057",
  genre: "Action | Sci-Fi | Superhero",
  year: "2019",
  rating: "6.8",
  language: "Japanese",
  description: "The beginning of Ultraman.",
  views: 1800
},
{
  id: 63,
  title: "Akuma Kun Season 1",
  poster: "/a63id.jpg",
  trailer: "https://www.youtube.com/embed/ZZQ7BaCunsw?si",
  telegramLink: "https://t.me/animeversebd/1084",
  genre: "Fantasy | Supernatural | Adventure",
  year: "2023",
  rating: "6.5",
  language: "Japanese/Hindi",
  description: "A demon's supernatural adventures.",
  views: 1600
},
{
  id: 64,
  title: "My Daemon Season 1",
  poster: "/a64id.jpg",
  trailer: "https://www.youtube.com/embed/vYTKsskxPV0?si",
  telegramLink: "https://t.me/animeversebd/1109",
  genre: "Fantasy | Sci-Fi | Drama",
  year: "2023",
  rating: "6.7",
  language: "Japanese/Hindi",
  description: "A girl and her daemon companion.",
  views: 1700
},
{
  id: 65,
  title: "Prison School Season 1",
  poster: "/a65id.jpg",
  trailer: "https://www.youtube.com/embed/l1v5WqCJva4?si",
  telegramLink: "https://t.me/animeversebd/1136",
  genre: "Comedy | Ecchi | School Life",
  year: "2015",
  rating: "7.6",
  language: "Japanese/Hindi",
  description: "Boys in an all-girls prison.",
  views: 1800
},
{
  id: 66,
  title: "Spy x Family Season 1",
  poster: "/a66id.jpg",
  trailer: "https://www.youtube.com/embed/fi_k0iAN8BE?si",
  telegramLink: "https://t.me/animeversebd/1161",
  genre: "Action | Comedy | Family",
  year: "2022",
  rating: "8.3",
  language: "Japanese/Hindi",
  description: "A spy, assassin, and psychic form a family.",
  views: 2000
},
{
  id: 67,
  title: "Mashle: Magic and Muscles Season 1",
  poster: "/a67id.jpg",
  trailer: "https://www.youtube.com/embed/nDHAgFP3wxU?si",
  telegramLink: "https://t.me/animeversebd/1212",
  genre: "Fantasy | Comedy | Action",
  year: "2023",
  rating: "7.4",
  language: "Japanese/Hindi",
  description: "Magic meets muscles in this adventure.",
  views: 1900
},
{
  id: 68,
  title: "My Love Story with Yamada-kun at Lv999",
  poster: "/a68id.jpg",
  trailer: "https://www.youtube.com/embed/im1jnkHA7wg?si",
  telegramLink: "https://t.me/animeversebd/1235",
  genre: "Romance | Comedy | Slice of Life",
  year: "2023",
  rating: "7.5",
  language: "Hindi/Japanese",
  description: "A gamer love story unfolds.",
  views: 1750
},
{
  id: 69,
  title: "Sgt. Stubby: An American Hero",
  poster: "/a69id.jpg",
  trailer: "https://www.youtube.com/embed/n3mbKogOWJ0?si",
  telegramLink: "https://t.me/animeversebd/1258",
  genre: "Adventure | Family | History",
  year: "2018",
  rating: "6.8",
  language: "English",
  description: "A dog's heroic journey in war.",
  views: 1600
},
{
  id: 70,
  title: "Stuart Little",
  poster: "/a70id.jpg",
  trailer: "https://www.youtube.com/embed/Wlo-sYrADlw?si",
  telegramLink: "https://t.me/animeversebd/1260",
  genre: "Adventure | Family | Comedy",
  year: "1999",
  rating: "6.7",
  language: "Hindi",
  description: "A mouse's adventures in the city.",
  views: 1550
},
{
  id: 71,
  title: "Stuart Little 2",
  poster: "/a71id.jpg",
  trailer: "https://www.youtube.com/embed/k--OdtbKyqE?si",
  telegramLink: "https://t.me/animeversebd/1262",
  genre: "Adventure | Family | Comedy",
  year: "2002",
  rating: "6.7",
  language: "Hindi",
  description: "Stuart's new adventure continues.",
  views: 1600
},
{
  id: 72,
  title: "Stuart Little 3",
  poster: "/a72id.jpg",
  trailer: "https://www.youtube.com/embed/trBgCyZpaa4?si",
  telegramLink: "https://t.me/animeversebd/1264",
  genre: "Adventure | Family | Comedy",
  year: "2005",
  rating: "6.7",
  language: "Hindi",
  description: "Stuart's final adventure.",
  views: 1650
},
{
  id: 73,
  title: "I Want to Eat Your Pancreas",
  poster: "/a73id.jpg",
  trailer: "https://www.youtube.com/embed/uqQySB0NO4U?si",
  telegramLink: "https://t.me/animeversebd/1270",
  genre: "Drama | Romance",
  year: "2018",
  rating: "8.1",
  language: "Hindi",
  description: "A touching love story.",
  views: 1700
},
{
  id: 74,
  title: "Suzume",
  poster: "/a74id.jpg",
  trailer: "https://www.youtube.com/embed/ciQc8lfvSm0?si",
  telegramLink: "https://t.me/animeversebd/1272",
  genre: "Fantasy | Adventure | Drama",
  year: "2022",
  rating: "7.6",
  language: "Hindi",
  description: "A girl's magical journey.",
  views: 1800
},
{
  id: 75,
  title: "Adam's Sweet Agony",
  poster: "/a75id.jpg",
  trailer: "https://www.youtube.com/embed/DzhRc0fsVrY?si",
  telegramLink: "https://t.me/animeversebd/1274",
  genre: "Romance | Sci-Fi | Adult Comedy",
  year: "2023",
  rating: "7.6",
  language: "Japanese",
  description: "A romantic sci-fi comedy.",
  views: 1750
},
{
  id: 76,
  title: "Bye Bye, Earth Season 1",
  poster: "/a76id.jpg",
  trailer: "https://www.youtube.com/embed/33rmUkfc7tM?si",
  telegramLink: "https://t.me/animeversebd/1289",
  genre: "Fantasy | Adventure | Drama",
  year: "2024",
  rating: "8.2",
  language: "Hindi",
  description: "An epic farewell to Earth.",
  views: 1900
},
{
  id: 77,
  title: "Dr. Stone Season 1",
  poster: "/a77id.jpg",
  trailer: "https://www.youtube.com/embed/Zlf8N7yrPwg?si",
  telegramLink: "https://t.me/animeversebd/1311",
  genre: "Animation | Comedy | Adventure",
  year: "2019",
  rating: "8.6",
  language: "English/Hindi",
  description: "Science rebuilds civilization.",
  views: 2100
},
{
  id: 78,
  title: "Dr. Stone: Stone Wars Season 2",
  poster: "/a78id.jpg",
  trailer: "https://www.youtube.com/embed/Nf8HZT3orUE?si",
  telegramLink: "https://t.me/animeversebd/1360",
  genre: "Animation | Action | Superhero",
  year: "2021",
  rating: "9.1",
  language: "English/Hindi",
  description: "The stone wars intensify.",
  views: 2300
},
{
  id: 79,
  title: "My Happy Marriage Season 1",
  poster: "/a79id.jpg",
  trailer: "https://www.youtube.com/embed/XoduKRPJeTI?si",
  telegramLink: "https://t.me/animeversebd/1383",
  genre: "Romance | Drama | Fantasy",
  year: "2023",
  rating: "7.6",
  language: "Japanese/Hindi",
  description: "A marriage of convenience becomes love.",
  views: 1850
},
{
  id: 80,
  title: "Lord of the Mysteries Season 1",
  poster: "/a80id.jpg",
  trailer: "https://www.youtube.com/embed/Pdv0Uoh-brs?si",
  telegramLink: "https://t.me/animeversebd/1410",
  genre: "Mystery | Fantasy | Action | Suspense",
  year: "2025",
  rating: "8.6",
  language: "Chinese/Hindi",
  description: "Mysteries unfold in a dark world.",
  views: 2200
},
{
  id: 81,
  title: "Sakamoto Days Season 1",
  poster: "/a81id.jpg",
  trailer: "https://www.youtube.com/embed/13pu4O72Rs4?si",
  telegramLink: "https://t.me/animeversebd/1429",
  genre: "Action | Comedy | Thriller",
  year: "2025",
  rating: "8.2",
  language: "Japanese/Hindi",
  description: "A retired assassin's peaceful days.",
  views: 2000
},
{
  id: 82,
  title: "Watchmen",
  poster: "/a82id.jpg",
  trailer: "https://www.youtube.com/embed/oUk6l8LCdCM?si",
  telegramLink: "https://t.me/animeversebd/1469",
  genre: "Action | Mystery | Drama | Superhero",
  year: "2009",
  rating: "7.6",
  language: "English/Hindi",
  description: "Superheroes in a dark world.",
  views: 1900
},
{
  id: 83,
  title: "Watchmen",
  poster: "/a83id.jpg",
  trailer: "https://www.youtube.com/embed/Gzt7e1eP2hs?si",
  telegramLink: "https://t.me/animeversebd/1471",
  genre: "Action | Mystery | Drama | Superhero",
  year: "2024",
  rating: "9.0",
  language: "English/Hindi",
  description: "A new take on Watchmen.",
  views: 2100
},
{
  id: 84,
  title: "Demon Slayer: Kimetsu no Yaiba – Infinity Castle",
  poster: "/a84id.jpg",
  trailer: "https://www.youtube.com/embed/x7uLutVRBfI?si",
  telegramLink: "https://t.me/animeversebd/1486",
  genre: "Anime | Action | Fantasy | Adventure",
  year: "2025",
  rating: "8.0",
  language: "Japanese",
  description: "The final battle begins.",
  views: 2000
},
{
  id: 85,
  title: "Tower of God Season 1",
  poster: "/a85id.jpg",
  trailer: "https://www.youtube.com/embed/9GJAE8Kj5Z4?si",
  telegramLink: "https://t.me/animeversebd/1488",
  genre: "Fantasy | Adventure | Mystery",
  year: "2020",
  rating: "7.6",
  language: "Japanese/Hindi",
  description: "Climbing the mysterious tower.",
  views: 1800
},
{
  id: 86,
  title: "Demon Slayer: Kimetsu no Yaiba – Infinity Castle",
  poster: "/a86id.jpg",
  trailer: "https://www.youtube.com/embed/0pdC1l6M8rU?si",
  telegramLink: "https://t.me/animeversebd/1503",
  genre: "Action | Fantasy | Adventure",
  year: "2025",
  rating: "9.2",
  language: "Hindi",
  description: "The ultimate demon slayer battle.",
  views: 2300
},
{
  id: 87,
  title: "The God of High School",
  poster: "/a87id.jpg",
  trailer: "https://www.youtube.com/embed/yKsM3eceKWk?si",
  telegramLink: "https://t.me/animeversebd/1505",
  genre: "Action | Fantasy | Martial Arts",
  year: "2020",
  rating: "7.2",
  language: "Japanese/Hindi",
  description: "High school martial arts tournament.",
  views: 1750
},
{
  id: 88,
  title: "Naruto Shippuden Season 1",
  poster: "/a88id.jpg",
  trailer: "https://www.youtube.com/embed/voAYyJwgQ3I?si",
  telegramLink: "https://t.me/animeversebd/1508",
  genre: "Animation | Action | Adventure | Fantasy",
  year: "2002",
  rating: "8.4",
  language: "Hindi",
  description: "Naruto's epic ninja journey.",
  views: 2200
},
{
  id: 89,
  title: "Oggy and the Cockroaches Season 1",
  poster: "/a89id.jpg",
  trailer: "https://www.youtube.com/embed/m67kaN-6VQk?si",
  telegramLink: "https://t.me/animeversebd/1526",
  genre: "Animation | Comedy | Family",
  year: "1998",
  rating: "7.4",
  language: "Hindi",
  description: "A cat's hilarious battles with cockroaches.",
  views: 1700
},
{
  id: 90,
  title: "Yoasobi Gurashi! (2024) Season 1",
  poster: "/a90id.jpg",
  trailer: "https://www.youtube.com/embed/OWHj6smKlsk?si",
  telegramLink: "https://t.me/animeversebd/1538",
  genre: "Animation | Romance | Slice of Life",
  year: "2024",
  rating: "7.4",
  language: "hindi dubbed",
  description: "দুই শৈশবের বন্ধুর অপ্রত্যাশিত মিলন—একটি রুমে বসবাস, একটি গোপন রহস্য, আর রাতের গভীরে উঠে আসা অনুভূতির গল্প।",
  views: 1700
},
{
  id: 91,
  title: "Naruto Shippuden  – Season 2 [Episode 1-32]",
  poster: "/a91id.jpg",
  trailer: "https://www.youtube.com/embed/hyapq_q_kvY?si",
  telegramLink: "https://t.me/animeversebd/1568",
  genre: "Animation | Adventure | Fantasy",
  year: "2004",
  rating: "8.4",
  language: "Hindi",
  description: "এক অনাথ বালক Naruto Uzumaki, যার শরীরে বন্দি আছে নয়-লেজওয়ালা শিয়াল (Nine-Tails Fox)—নিজেকে স্বীকৃতি দেওয়ানোর জন্য শুরু করে হোকাগে হওয়ার স্বপ্নযাত্রা। ",
  views: 1700
},
{
  id: 92,
  title: "Yoasobi Gurashi! (2024) Season 1 part 2",
  poster: "/a92id.jpg",
  trailer: "https://www.youtube.com/embed/OWHj6smKlsk?si",
  telegramLink: "https://t.me/animeversebd/1592",
  genre: "Animation | Romance | Slice of Life",
  year: "2024",
  rating: "7.4",
  language: "hindi dubbed",
  description: "দুই শৈশবের বন্ধুর অপ্রত্যাশিত মিলন—একটি রুমে বসবাস, একটি গোপন রহস্য, আর রাতের গভীরে উঠে আসা অনুভূতির গল্প।",
  views: 1700
},
{
  id: 93,
  title: "Fire Force (Season 2 – 2020)",
  poster: "/a93id.jpg",
  trailer: "https://www.youtube.com/embed/Clr3JzxtAU4?si",
  telegramLink: "https://t.me/animeversebd/1597",
  genre: "Animation | Supernatural | Shounen",
  year: "2020",
  rating: "7.6",
  language: "Hindi",
  description: "Special Fire Force Company 8 আবারও নামছে নতুন শত্রুর মুখোমুখি হতে—Infernals দমন, White-Clad এর ষড়যন্ত্র আর শিনরার অতীতের রহস্য উন্মোচনের লড়াই। ",
  views: 1700
},
{
  id: 94,
  title: "Motu Patlu (Season 1 – Bangla Dubbed)",
  poster: "/a94id.jpg",
  trailer: "https://www.youtube.com/embed/nb7eXOnflw4?si",
  telegramLink: "https://t.me/animeversebd/1648",
  genre: "Animation | Comedy | Adventure",
  year: "2015",
  rating: "6.5",
  language: "Dubbed in Bangla",
  description: "ফুরফুরিগঞ্জের দুষ্টু জুটি—মোটু আর পাতলু, মজার মজার কাণ্ডকারখানা আর হাস্যকর অ্যাডভেঞ্চারে ভরপুর।",
  views: 1700
},
{
  id: 95,
  title: "Naruto Shippuden  – Season 3 [Episode 1-18]",
  poster: "/a95id.jpg",
  trailer: "https://www.youtube.com/embed/-1TKGtX8lJY?si",
  telegramLink: "https://t.me/animeversebd/1650",
  genre: "Animation | Comedy | Family",
  year: "2005",
  rating: "7.4",
  language: "Hindi",
  description: "এক অনাথ বালক Naruto Uzumaki, যার শরীরে বন্দি আছে নয়-লেজওয়ালা শিয়াল (Nine-Tails Fox)—নিজেকে স্বীকৃতি দেওয়ানোর জন্য শুরু করে হোকাগে হওয়ার স্বপ্নযাত্রা। ",
  views: 1700
},
{
  id: 96,
  title: "Marvel Zombies: Season 1 (2025)",
  poster: "/a96id.jpg",
  trailer: "https://www.youtube.com/embed/UPAr5zef2Pk?si",
  telegramLink: "https://t.me/animeversebd/1693",
  genre: "Animation | Horror | Superhero",
  year: "2025",
  rating: "8.4",
  language: "English",
  description: "এক বিকল্প বাস্তবতায় পৃথিবীজুড়ে ছড়িয়ে পড়ে জম্বি ভাইরাস—যেখানে পরিচিত সুপারহিরোরা নিজেরাই হয়ে যায় ভয়ঙ্কর শিকারি।",
  views: 1700
},
{
  id: 97,
  title: "Doraemon: Nobita’s Art World Tales (2024)",
  poster: "/a97id.jpg",
  trailer: "https://www.youtube.com/embed/3kW9tWoJfeM?si",
  telegramLink: "https://t.me/animeversebd/1784",
  genre: "Animation | Adventure | Fantasy",
  year: "2024",
  rating: "9.7",
  language: "Japanese",
  description: "নোবিতা ও ডোরেমন এবার ঘুরে বেড়ায় চিত্রকলার জগতে! রঙ, কল্পনা আর রোমাঞ্চে ভরা এই সিনেমা ছোট-বড় সবার মন ছুঁয়ে যাবে।",
  views: 1700
},
{
  id: 98,
  title: "Naruto Shippuden  – Season 4 [Episode 1-17]",
  poster: "/a98id.jpg",
  trailer: "https://www.youtube.com/embed/zD8GPACmks8?si",
  telegramLink: "https://t.me/animeversebd/1786",
  genre: "Animation | Comedy | Family",
  year: "2007",
  rating: "7.4",
  language: "Hindi",
  description: "এক অনাথ বালক Naruto Uzumaki, যার শরীরে বন্দি আছে নয়-লেজওয়ালা শিয়াল (Nine-Tails Fox)—নিজেকে স্বীকৃতি দেওয়ানোর জন্য শুরু করে হোকাগে হওয়ার স্বপ্নযাত্রা। ",
  views: 1700
},
{
  id: 99,
  title: "Tom and Jerry – Season 1 (1940-Present)",
  poster: "/a99id.jpg",
  trailer: "https://www.youtube.com/embed/hgLV7qyWU04?si",
  telegramLink: "https://t.me/animeversebd/1824",
  genre: "Animation | Comedy | Family",
  year: "1940",
  rating: "8.4",
  language: "English",
  description: "চিরচেনা বিড়াল-ইঁদুরের দুষ্টুমি, মারামারি আর হাস্যরসের অনন্ত যুদ্ধ—Tom & Jerry মানেই শৈশবের স্মৃতি!",
  views: 1700
},
{
  id: 100,
  title: "Motu Patlu vs the ghost house.",
  poster: "/a100id.jpg",
  trailer: "https://www.youtube.com/embed/k0N7N09Viy8?si",
  telegramLink: "https://t.me/animeversebd/1826",
  genre: "Animation | Comedy | Kids",
  year: "1998",
  rating: "6.9",
  language: "Bangla Dubbed",
  description: "ফুরফুরে ফুরফুরি নগরের দুই বন্ধু মটু-পাটলুর দুষ্টুমি ও হাসির অভিযান—প্রতিটি পর্বেই নতুন কাণ্ড!",
  views: 1700
},
{
  id: 101,
  title: "Naruto Shippuden  – Season 5 [Episode 1-24]",
  poster: "/a101id.jpg",
  trailer: "https://www.youtube.com/embed/hyapq_q_kvY?si",
  telegramLink: "https://t.me/animeversebd/1828",
  genre: "Animation | Adventure | Fantasy",
  year: "2008",
  rating: "8.4",
  language: "Hindi",
  description: "এক অনাথ বালক Naruto Uzumaki, যার শরীরে বন্দি আছে নয়-লেজওয়ালা শিয়াল (Nine-Tails Fox)—নিজেকে স্বীকৃতি দেওয়ানোর জন্য শুরু করে হোকাগে হওয়ার স্বপ্নযাত্রা। ",
  views: 1700
},
{
  id: 102,
  title: "One Punch Man – Season 1 (2015)",
  poster: "/a102id.jpg",
  trailer: "https://www.youtube.com/embed/iYPDxVoLNS8?si",
  telegramLink: "https://t.me/animeversebd/1882",
  genre: "Animation | Comedy | Superhero",
  year: "2015",
  rating: "8.7",
  language: "Hindi",
  description: "সাইতামা নামের এক সাধারণ মানুষ, যে মাত্র এক ঘুষিতে হারিয়ে দেয় যেকোনো শত্রুকে! 💪😂তবে শক্তির পাশাপাশি তার একঘেয়ে জীবনের হাস্যরসই এই সিরিজের মূল আকর্ষণ। ",
  views: 1700
},
{
  id: 103,
  title: "One Punch Man – Season 2",
  poster: "/a103id.jpg",
  trailer: "https://www.youtube.com/embed/mS1FcNK7VnI?si",
  telegramLink: "https://t.me/animeversebd/1910",
  genre: "Animation | Comedy | Superhero",
  year: "2019",
  rating: "8.1",
  language: "Hindi",
  description: "সাইতামার এক ঘুষিতেই শেষ—কিন্তু এইবার লড়াই আরও কঠিন, আর শত্রুরা আরও বিপজ্জনক। ",
  views: 1700
},
{
  id: 104,
  title: "Naruto Shippuden – Season 6 [episode 1-31]",
  poster: "/a104id.jpg",
  trailer: "https://www.youtube.com/embed/6kNR6fnoHrU?si",
  telegramLink: "https://t.me/animeversebd/1921",
  genre: "Animation | Comedy | Fantasy",
  year: "2009",
  rating: "8.7",
  language: "Hindi",
  description: "নারুটো আর জিরাইয়ার যাত্রা—নিজের শক্তি, ভালোবাসা আর আত্মত্যাগের মহাকাব্য। ",
  views: 1700
},
{
  id: 105,
  title: "Dr. Stone – Season 4: Science Future Arc (ドクターストーン)",
  poster: "/a105id.jpg",
  trailer: "https://www.youtube.com/embed/hvX-cYLRAfY?si",
  telegramLink: "https://t.me/animeversebd/1987",
  genre: "Animation | Comedy | Sci-Fi",
  year: "2025",
  rating: "8.2",
  language: "Hindi",
  description: "সেনকু এবং তার টিম এবার বিজ্ঞানের শক্তিতে পৌঁছে যাচ্ছে সভ্যতার ভবিষ্যতের দোরগোড়ায়।",
  views: 1700
},
{
  id: 106,
  title: "Rent a Girlfriend – Season 1 (彼女、お借りします)",
  poster: "/a106id.jpg",
  trailer: "https://www.youtube.com/embed/8r3h_CI1C3s?si",
  telegramLink: "https://t.me/animeversebd/2038",
  genre: "Animation | Comedy | Slice of Life",
  year: "2020",
  rating: "7.1",
  language: "Hindi",
  description: "rent a girlfriend story",
  views: 1700
},
{
  id: 107,
  title: "Solo Leveling: Season 1 (2024)",
  poster: "/a107id.jpg",
  trailer: "https://www.youtube.com/embed/-tJMyIXjn9I?si",
  telegramLink: "https://t.me/animeversebd/2065",
  genre: "Animation | Comedy | Supernatural",
  year: "2024",
  rating: "8.6",
  language: "Hindi",
  description: "দুর্বল হান্টার জিনউ সাং একদিন সিস্টেম নামক রহস্যময় ক্ষমতা পায়, যা তাকে ধীরে ধীরে বিশ্বের সবচেয়ে শক্তিশালী হান্টারে পরিণত করে।",
  views: 1700
},
{
  id: 108,
  title: "Solo Leveling: Season 2 – Arise from the Shadow (2025)",
  poster: "/a108id.jpg",
  trailer: "https://www.youtube.com/embed/Mgk5_MXodvY?si",
  telegramLink: "https://t.me/animeversebd/2072",
  genre: "Animation | Comedy | Adventure",
  year: "2025",
  rating: "9.0",
  language: "Hindi",
  description: "প্রথম সিজনের পর জিনউ সাং এখন এক অপ্রতিরোধ্য ছায়া সেনাবাহিনীর অধিপতি। তার সামনে নতুন চ্যালেঞ্জ—দেবতাদের সঙ্গে যুদ্ধের সূচনা।",
  views: 1700
},
{
  id: 109,
  title: "Naruto Shippuden – Season 7 (2009) [Episode1-08]",
  poster: "/a109id.jpg",
  trailer: "https://www.youtube.com/embed/6kNR6fnoHrU?si",
  telegramLink: "https://t.me/animeversebd/2080",
  genre: "Animation | Comedy | Fantasy",
  year: "2009",
  rating: "8.7",
  language: "Hindi",
  description: "নারুতো ও তার সঙ্গীরা নতুন মিশনে নামে এক রহস্যময় দ্বীপে, যেখানে প্রতিটি পদক্ষেপে অপেক্ষা করছে নতুন বিপদ আর নিজের ভেতরের অন্ধকারের মুখোমুখি হওয়ার লড়াই।",
  views: 1700
},
{
  id: 110,
  title: "Naruto Shippuden – Season 8 (2009-2010)[Episode1-24]",
  poster: "/a110id.jpg",
  trailer: "https://www.youtube.com/embed/zD8GPACmks8?si",
  telegramLink: "https://t.me/animeversebd/2101",
  genre: "Animation | Comedy | Fantasy",
  year: "2010",
  rating: "7.4",
  language: "Hindi",
  description: "এই সিজনে নারুতো মুখোমুখি হয় ভয়ঙ্কর পেইনের, যার আক্রমণে কনোহা গ্রাম ধ্বংসের মুখে পড়ে। কিন্তু অদম্য সাহস আর বন্ধুত্বের শক্তিতে নারুতো প্রমাণ করে — সত্যিকারের নিনজা কখনও হার মানে না। ",
  views: 1700
},
{
  id: 111,
  title: "classroom of the elite (Season 1)",
  poster: "/a111id.jpg",
  trailer: "https://www.youtube.com/embed/bXoll51Iig0?si",
  telegramLink: "https://t.me/animeversebd/2199",
  genre: "Animation | drama | sci-fi",
  year: "2017",
  rating: "7.9",
  language: "Hindi",
  description: "গল্পের সারসংক্ষেপ: একটি বিশেষ উচ্চবিদ্যালয়ে ছাত্রদের মধ্যে প্রতিযোগিতা ও আত্মবিশ্বাসের চূড়ান্ত পরীক্ষা—যেখানে কৌশল এবং বন্ধুত্বের মাধ্যমে তারা নিজেদের পরিচয় তৈরি করে।",
  views: 1700
},
{
  id: 112,
  title: "classroom of the elite (Season 2)",
  poster: "/a112id.jpg",
  trailer: "https://www.youtube.com/embed/hDzuuQJG6Ss?si",
  telegramLink: "https://t.me/animeversebd/2226",
  genre: "Animation | sci-fi | drama",
  year: "2022",
  rating: "8.0",
  language: "Hindi",
  description: "দ্বিতীয় সিজনে, নতুন চ্যালেঞ্জ এবং প্রতিযোগিতার মুখোমুখি হয় ছাত্ররা, যেখানে তাদের বুদ্ধিমত্তা এবং বিচক্ষণতা আবারও পরীক্ষিত হয়।",
  views: 1700
},
{
  id: 113,
  title: "Haikyuu!! – Season 1 (2014)",
  poster: "/a113id.jpg",
  trailer: "https://www.youtube.com/embed/Bp7e_Vi0WVs?si",
  telegramLink: "https://t.me/animeversebd/2255",
  genre: "Animation | Sports | Comedy",
  year: "2014",
  rating: "8.7",
  language: "Hindi",
  description: "এই সিজনে দেখা যায় শোয়ো হিনাতাকে, এক ছোটখাটো কিন্তু স্বপ্নবাজ খেলোয়াড়, যে ভলিবলে কিংবদন্তি হতে চায়। প্রতিদ্বন্দ্বী কাগেয়ামার সঙ্গে অপ্রত্যাশিত জুটি গড়ে তারা কারাসুনো হাই স্কুলে নতুন করে দল গড়ে তোলে — যেখানে বন্ধুত্ব, পরিশ্রম আর আত্মবিশ্বাসই হয়ে ওঠে জয়ের আসল চাবিকাঠি।",
  views: 1700
},
{
  id: 114,
  title: "My Mother: The Animation",
  poster: "/a114id.jpg",
  trailer: "https://www.youtube.com/embed/nE08t1HQwkU?si",
  telegramLink: "https://t.me/animeversebd/2306",
  genre: "Animation | Adventure | Adult",
  year: "2025",
  rating: "8.4",
  language: "english",
  description: "এই শিরোনামটি প্রাপ্তবয়স্ক ও যৌন বিষয়বস্তুপূর্ণ (adult explicit content) হওয়ায় আমি এর কোনো শিরোনাম বা বিবরণ তৈরি করতে পারব না।",
  views: 1700
},
{
  id: 115,
  title: "Naruto Shippuden: Season 9 (2010)",
  poster: "/a115id.jpg",
  trailer: "https://www.youtube.com/embed/3NtW5gyNeaI?si",
  telegramLink: "https://t.me/animeversebd/2308",
  genre: "Action | Adventure | Anime",
  year: "2010",
  rating: "8.7",
  language: "hindi",
  description: "নিনজা দুনিয়ার নতুন চ্যালেঞ্জ, নতুন বন্ধুত্ব আর আত্মত্যাগের গল্প — নারুতো নিজের স্বপ্নের আরও কাছে পৌঁছে যায়। ",
  views: 1700
},
{
  id: 116,
  title: "Bastard!! -Heavy Metal, Dark Fantasy- (Season 1)",
  poster: "/a116id.jpg",
  trailer: "https://www.youtube.com/embed/alXQXal8dw4?si",
  telegramLink: "https://t.me/animeversebd/2357",
  genre: "Action | Fantasy | Adventure",
  year: "2024",
  rating: "7.1",
  language: "Hindi",
  description: "এক অন্ধকার জাদুকর আর ভয়ঙ্কর রাজ্যের লড়াই — ধ্বংস আর মুক্তির সীমান্তে দাঁড়িয়ে! ",
  views: 1700
},
{
  id: 117,
  title: "Bastard!! -Heavy Metal, Dark Fantasy- (Season 2)",
  poster: "/a117id.jpg",
  trailer: "https://www.youtube.com/embed/UP3FnxiT8RI?si",
  telegramLink: "https://t.me/animeversebd/2366",
  genre: "Dark Fantasy | Magic | Shounen",
  year: "2025",
  rating: "7.3",
  language: "Hindi",
  description: "আগুনে ফিরে এলো দার্ক শ্নাইডার — এইবার পৃথিবী রক্ষার নামে রক্তগন্ধ যুদ্ধ ",
  views: 1700
},
{
  id: 118,
  title: "Takopi’s Original Sin (Season 1)",
  poster: "/a118id.jpg",
  trailer: "https://www.youtube.com/embed/pDNkpj2ERao?si",
  telegramLink: "https://t.me/animeversebd/2373",
  genre: "Action | Sci-Fi | Drama",
  year: "2010",
  rating: "8.4",
  language: "hindi",
  description: "এক ছোট্ট এলিয়েন আর এক শিশুর দুঃখভরা পৃথিবী — যেখানে নির্দোষতাও অপরাধ  ",
  views: 1700
},
{
  id: 119,
  title: "Heroines Run the Show (Season 1)",
  poster: "/a119id.jpg",
  trailer: "https://www.youtube.com/embed/y20zBmpuSVY?si",
  telegramLink: "https://t.me/animeversebd/2377",
  genre: "Animation | School | Music",
  year: "2025",
  rating: "7.5",
  language: "Hindi",
  description: "মিউজিক আর ভালোবাসার টানাপোড়েনে এক সাধারণ মেয়ের অসাধারণ যাত্রা ",
  views: 1700
},
{
  id: 120,
  title: "Hunter x Hunter (Season 2)",
  poster: "/a120id.jpg",
  trailer: "https://www.youtube.com/embed/aa8XPmXboOw?si",
  telegramLink: "https://t.me/animeversebd/2404",
  genre: "Animation | Fantasy | Adventure",
  year: "2023",
  rating: "9.0",
  language: "Hindi",
  description: "গন আর কিলুয়া এবার প্রবেশ করে ইয়র্কনিউ শহরের অপরাধের জগতে ",
  views: 1700
},
{
  id: 121,
  title: "Food Wars!: Shokugeki no Soma (Season 1)",
  poster: "/a121id.jpg",
  trailer: "https://www.youtube.com/embed/z4vihPwUBls?si",
  telegramLink: "https://t.me/animeversebd/2408",
  genre: "Animation | Comedy | Family",
  year: "2025",
  rating: "8.2",
  language: "Hindi",
  description: "রান্নার ময়দানে যুদ্ধ! সোমা ইউকিহিরার স্বপ্ন – বিশ্বের সেরা শেফ হওয়া ",
  views: 1700
},
{
  id: 122,
  title: "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs (Season 1)",
  poster: "/a122id.jpg",
  trailer: "https://www.youtube.com/embed/zOdeGIrQlQ8?si",
  telegramLink: "https://t.me/animeversebd/2415",
  genre: "Animation | Comedy | Adventure",
  year: "2025",
  rating: "7.6",
  language: "Hindi",
  description: "এক গেমার হঠাৎ ঢুকে পড়ে নিজের খেলা দুনিয়ায় — এখন টিকে থাকাটাই তার মিশন ",
  views: 1700
},
{
  id: 123,
  title: "Shinchan Spin-Off (Season 3)",
  poster: "/a123id.jpg",
  trailer: "https://www.youtube.com/embed/g1Y1v96KGXA?si",
  telegramLink: "https://t.me/animeversebd/2420",
  genre: "Animation | Comedy | Fantasy",
  year: "2024",
  rating: "7.0",
  language: "Hindi",
  description: "শিনচানের পাগলামি এবার আরও রঙিন – ছোট্ট ছেলেটির বড় বড় দুষ্টুমি ",
  views: 1700
},
{
  id: 124,
  title: "Shinchan Spin-Off (Season 4)",
  poster: "/a124id.jpg",
  trailer: "https://www.youtube.com/embed/fcVy846GFXA?si",
  telegramLink: "https://t.me/animeversebd/2422",
  genre: "Animation | Comedy | Family",
  year: "2025",
  rating: "7.2",
  language: "Hindi",
  description: "পরিবার, বন্ধুত্ব আর হাসির বন্যা – শিনচান ফিরেছে নতুন অ্যাডভেঞ্চার নিয়ে ",
  views: 1700
},
{
  id: 125,
  title: "Vinland Saga (Season 1)",
  poster: "/a125id.jpg",
  trailer: "https://www.youtube.com/embed/FlPs7EdBmNA?si",
  telegramLink: "https://t.me/animeversebd/2424",
  genre: "Animation | Adventure | Family",
  year: "2024",
  rating: "8.8",
  language: "hindi",
  description: "ভাইকিংদের নিষ্ঠুর পৃথিবীতে থরফিনের প্রতিশোধ আর স্বাধীনতার কাহিনি ",
  views: 1700
},
{
  id: 126,
  title: "Vinland Saga (Season 2)",
  poster: "/a126id.jpg",
  trailer: "https://www.youtube.com/embed/cfme7JslzoQ?si",
  telegramLink: "https://t.me/animeversebd/2435",
  genre: "Animation | Adventure | Historical",
  year: "2025",
  rating: "9.0",
  language: "hindi",
  description: "প্রতিশোধ শেষে আসে আত্মঅনুসন্ধান — এক যোদ্ধার আত্মার শান্তির পথ ",
  views: 1700
},
{
  id: 127,
  title: "Haikyuu!! (Season 2)",
  poster: "/a127id.jpg",
  trailer: "https://www.youtube.com/embed/3AJNuyXbCO4?si",
  telegramLink: "https://t.me/animeversebd/2442",
  genre: "Animation | Sports | Shounen",
  year: "2016",
  rating: "8.9",
  language: "Hindi",
  description: "নতুন টুর্নামেন্ট, নতুন প্রতিদ্বন্দ্বী — কারাসুনোর দল উড়ছে আরও উঁচুতে! ",
  views: 1700
},
{
  id: 128,
  title: "Haikyuu!! (Season 3)",
  poster: "/a128id.jpg",
  trailer: "https://www.youtube.com/embed/3AJNuyXbCO4?si",
  telegramLink: "https://t.me/animeversebd/2495",
  genre: "Animation | Sports | Teamwork",
  year: "2018",
  rating: "9.1",
  language: "Hindi",
  description: "এক ম্যাচ, এক লক্ষ্য — শিরাটোরিজাওয়ার বিরুদ্ধে লড়াই, যেখানে প্রতিটি পয়েন্টই জীবন-মরণ! ",
  views: 1700
},
{
  id: 129,
  title: "Hunter x Hunter (Season 3 – 2012)",
  poster: "/a129id.jpg",
  trailer: "https://www.youtube.com/embed/aa8XPmXboOw?si",
  telegramLink: "https://t.me/animeversebd/2522",
  genre: "Action | Fantasy | Adventure",
  year: "2012",
  rating: "9.0",
  language: "Hindi",
  description: "গন ও কিলুয়া নতুন চ্যালেঞ্জে নামছে — গ্রিড আইল্যান্ডের রহস্যে লুকিয়ে আছে শক্তি, বন্ধুত্ব আর সাহসের গল্প ",
  views: 1700
},
{
  id: 130,
  title: "Hunter x Hunter (Season 4 – 2013)",
  poster: "/a130id.jpg",
  trailer: "https://www.youtube.com/embed/aa8XPmXboOw?si",
  telegramLink: "https://t.me/animeversebd/2527",
  genre: "Dark Fantasy | Magic | Shounen",
  year: "2013",
  rating: "9.2",
  language: "Hindi",
  description: "কিমেরা অ্যান্ট আর্ক — মানবতা, ত্যাগ আর নায়কোচিত যুদ্ধের এক আবেগময় অধ্যায় ",
  views: 1700
},
{
  id: 131,
  title: "Naruto Shippuden (Season 10 – 2011)[EP-1-25]",
  poster: "/a131id.jpg",
  trailer: "https://www.youtube.com/embed/6kNR6fnoHrU?si",
  telegramLink: "https://t.me/animeversebd/2532",
  genre: "Action | Sci-Fi | Drama",
  year: "2011",
  rating: "8.7",
  language: "hindi",
  description: "যুদ্ধের প্রান্তে দাঁড়িয়ে নারুতো শিখছে আসল নিনজা হওয়ার অর্থ — আত্মত্যাগ, বিশ্বাস আর বন্ধুত্বের শক্তি ",
  views: 1700
},
{
  id: 132,
  title: "Chainsaw Man (2025)",
  poster: "/a132id.jpg",
  trailer: "https://www.youtube.com/embed/HUlu-nbmFjU?si",
  telegramLink: "https://t.me/animeversebd/2588",
  genre: "Action | Horror | Supernatural",
  year: "2025",
  rating: "8.8",
  language: "Hindi",
  description: "এক ছেলেকে ঘিরে রক্তমাখা গল্প, যে নিজের দেহকে রূপান্তর করতে পারে চেইনসো দানবে! শয়তানদের ধ্বংস করতে তার শুরু হয় এক ভয়ংকর যুদ্ধ।",
  views: 1700
},
{
  id: 133,
  title: "Naruto Season 11 (2011)",
  poster: "/a133id.jpg",
  trailer: "https://www.youtube.com/embed/eka84VDAHsI?si",
  telegramLink: "https://t.me/animeversebd/2590",
  genre: "Action | Adventure | Fantasy",
  year: "2011",
  rating: "9.2",
  language: "Hindi",
  description: "নিনজা জগতের নতুন মিশন ও লড়াই — বন্ধুত্ব, ত্যাগ আর নায়কোচিত সাহসের এক অনন্য অধ্যায়। ",
  views: 1700
},
{
  id: 134,
  title: "Haikyuu!! Season 4: To the Top (2020)",
  poster: "/a134id.jpg",
  trailer: "https://www.youtube.com/embed/Z_eI8k0yB8Q?si",
  telegramLink: "https://t.me/animeversebd/2635",
  genre: "Sports | Friendship | Drama",
  year: "2020",
  rating: "8.8",
  language: "hindi",
  description: "হিনাতা ও কাগেয়ামা জাতীয় প্রতিযোগিতায় পৌঁছানোর স্বপ্ন পূরণের পথে নতুন প্রতিদ্বন্দ্বী ও চ্যালেঞ্জের মুখোমুখি হয়। ",
  views: 1700
},
{
  id: 135,
  title: "Kurukshetra (Season 1 - 2024) EP-01-18 added☑️",
  poster: "/a135id.jpg",
  trailer: "https://www.youtube.com/embed/AEP84U6ApSI?si",
  telegramLink: "https://t.me/animeversebd/2664",
  genre: "Action | Political | Thriller",
  year: "2024",
  rating: "7.4",
  language: "Hindi",
  description: "রাজনীতি, ক্ষমতা আর প্রতিশোধের যুদ্ধ— যেখানে প্রত্যেক চরিত্র নিজের সত্যকে প্রমাণ করতে নামে আধুনিক কুরুক্ষেত্-এর ময়দানে। ",
  views: 1700
},
{
  id: 136,
  title: "Naruto: Shippuden – Season 12 (2011–2012)",
  poster: "/a136id.jpg",
  trailer: "https://www.youtube.com/embed/L8M9j98V-oQ?si",
  telegramLink: "https://t.me/animeversebd/2703",
  genre: "Action | Fantasy | Adventure",
  year: "2012",
  rating: "8.7",
  language: "Hindi",
  description: "নারুটো আর তার দল শান্তির জন্য নতুন মিশনে নামে, যেখানে রাজনৈতিক ষড়যন্ত্র আর পুরনো শত্রুরা আবারও ছায়া ফেলে। ",
  views: 1700
},
{
  id: 137,
  title: "Doraemon the Movie: Nobita's Earth Symphony (2024)",
  poster: "/a137id.jpg",
  trailer: "https://www.youtube.com/embed/hwN3QpGGEe0?si",
  telegramLink: "https://t.me/animeversebd/2774",
  genre: "Family | Animation | Adventure",
  year: "2025",
  rating: "7.5",
  language: "Hindi",
  description: "নোবিতা ও ডোরেমনের দুনিয়ায় এক রহস্যময় সুরের উৎস পৃথিবীকে বিপদের মুখে ফেলে। বন্ধুদের নিয়ে নোবিতা শুরু করে এক নতুন অভিযাত্রা—যেখানে সঙ্গীতই হতে পারে পৃথিবী রক্ষার একমাত্র উপায়।",
  views: 1700
},
{
  id: 138,
  title: "Mother-in-Love 2025",
  poster: "/a138id.jpg",
  trailer: "https://www.youtube.com/embed/56sSGP2J2Wc?si",
  telegramLink: "https://t.me/animeversebd/2776",
  genre: "Romance | Adult | Drama",
  year: "2025",
  rating: "9.2",
  language: "japanese",
  description: "পরিবারের জটিল সম্পর্কের ভিতরে লুকিয়ে থাকা আকর্ষণ, আবেগ আর নিষিদ্ধ টানাপোড়েনকে ঘিরে গল্প এগোয়।",
  views: 1700
},
{
  id: 139,
  title: "Naruto Shippuden – Season 13 (2012)",
  poster: "/a139id.jpg",
  trailer: "https://www.youtube.com/embed/0e_Qnum4dRw?si",
  telegramLink: "https://t.me/animeversebd/2782",
  genre: "Action | Adventure | Fantasy",
  year: "2012",
  rating: "8.7",
  language: "hindi",
  description: "গ্রেট নিনজা ওয়ার শুরু হওয়ার সাথে সাথে নারুতো জানতে পারে শত্রুরা তার শক্তিকে ব্যবহার করতে চাইছে। আরেকদিকে, এলাইড শিনোবি ফোর্স মৃত যোদ্ধাদের এডো টেন্সেই আর্মির বিরুদ্ধে বাঁচার লড়াই চালায়। দুনিয়াকে রক্ষা করতে নারুতো নামছে প্রকৃত যুদ্ধের ময়দানে।",
  views: 1700
},
{
  id: 140,
  title: "My Hero Academia: Vigilantes",
  poster: "/a140id.jpg",
  trailer: "https://www.youtube.com/embed/i-8-xFFIOoM?si",
  telegramLink: "https://t.me/animeversebd/2826",
  genre: "Action | Superhero | Crime",
  year: "2024",
  rating: "8.7",
  language: "japanese",
  description: "মূল My Hero Academia ঘটনার আগের সময়ে, কোইচি নামে এক সাধারণ যুবক বিশেষ ক্ষমতা নিয়ে আইনের বাইরে থেকেই অপরাধ দমনে নেমে পড়ে। তার সঙ্গে যোগ দেয় আরও কিছু আন্ডারগ্রাউন্ড হিরো— যারা মিলে শহরকে রক্ষা করে অফিসিয়াল হিরো সিস্টেমের ছায়ায়।",
  views: 1700
},
{
  id: 141,
  title: "Tokyo Revengers – Season 2 (2023)",
  poster: "/a141id.jpg",
  trailer: "https://www.youtube.com/embed/eNZSurcYTW8?si",
  telegramLink: "https://t.me/animeversebd/2833",
  genre: "Action | Time-Travel | Drama",
  year: "2023",
  rating: "7.8",
  language: "English",
  description: "তাকেমিচি আবার ফিরে যায় অতীতে—এইবার Christmas Showdown আর্কে মুখোমুখি হয় ভয়ংকর ব্ল্যাক ড্রাগন গ্যাংয়ের। বন্ধুত্ব, বিশ্বাস আর রক্তাক্ত প্রতিশোধের লড়াইয়ে প্রতিটি ভুল সিদ্ধান্ত বদলে দিতে পারে ভবিষ্যতের জীবন-মরণ ভাগ্য।",
  views: 1700
},
{
  id: 142,
  title: "Up (2009)",
  poster: "/a142id.jpg",
  trailer: "https://www.youtube.com/embed/ORFWdXl_zJ4?si",
  telegramLink: "https://t.me/animeversebd/2862",
  genre: "Animation | Adventure | Comedy",
  year: "2009",
  rating: "8.3",
  language: "English/hindi",
  description: "এক বুড়ো মানুষ তার স্ত্রীর শেষ ইচ্ছে পূরণ করতে হাজারো বেলুন বেঁধে বাড়িটিকে উড়িয়ে দেন আকাশে—কিন্তু সঙ্গে জড়িয়ে যায় এক ছোট্ট বালক স্কাউটের মজাদার, আবেগী ও জীবন বদলে দেওয়া অ্যাডভেঞ্চার।",
  views: 1700
},
{
  id: 143,
  title: "Naruto Shippuden – Season 14 (2012)",
  poster: "/a143id.jpg",
  trailer: "https://www.youtube.com/embed/0e_Qnum4dRw?si",
  telegramLink: "https://t.me/animeversebd/2864",
  genre: "Action | Fantasy | Adventure",
  year: "2012",
  rating: "8.5",
  language: "Hindi",
  description: "চতুর্থ মহান নিনজা যুদ্ধে উত্তেজনা চরমে—নারুতো ধীরে ধীরে নিজের শক্তি, ইতিহাস ও ভাগ্যের সত্যের মুখোমুখি হয়, যেখানে প্রতিটি লড়াই তার ভবিষ্যত নির্ধারণ করে।",
  views: 1700
},
{
  id: 144,
  title: "One Piece – The Grand Voyage ",
  poster: "/a144id.jpg",
  trailer: "https://www.youtube.com/embed/Hy_twM7sLjk?si",
  telegramLink: "https://t.me/animeversebd/2917",
  genre: "Animation | Adventure | Action",
  year: "2024",
  rating: "8.2",
  language: "Hindi",
  description: "এক নতুন রহস্যময় সমুদ্র অঞ্চলে অভিযানে বের হয় লুফি ও তার স্ট্র হ্যাট পাইরেটস দল—যেখানে অপেক্ষা করছে বিপজ্জনক শত্রু, প্রাচীন ধন ও বন্ধুত্বের আসল পরীক্ষা।",
  views: 1700
},
{
  id: 145,
  title: "Tony’s Heroine (2009)",
  poster: "/a145id.jpg",
  trailer: "https://www.youtube.com/embed/IH8AzAF1jM4?si",
  telegramLink: "https://t.me/animeversebd/2921",
  genre: "Action | Comedy | Family",
  year: "2009",
  rating: "5.0",
  language: "Japanese",
  description: "এক তরুণ নারী নিজেকে মাফিয়া ও আন্ডারওয়ার্ল্ডের সংঘাতে জড়িয়ে ফেলে যখন টনি নামের রহস্যময় এক ব্যক্তির সঙ্গে তার পরিচয় হয়। বাঁচতে হলে তাকে সত্য উদঘাটন করতেই হবে।",
  views: 1700
},
{
  id: 146,
  title: "Young Justice – Season 1 (2010)",
  poster: "/a146id.jpg",
  trailer: "https://www.youtube.com/embed/SQi0Ll6vNpM?si",
  telegramLink: "https://t.me/animeversebd/2927",
  genre: "Animation | Adventure | Family",
  year: "2024",
  rating: "8.6",
  language: "hindi",
  description: "ডিসি ইউনিভার্সের কিশোর সুপারহিরোরা গোপন টিম গঠন করে নিজেদের যোগ্যতা প্রমাণ করতে নামে বিপজ্জনক মিশনে।",
  views: 1700
},
{
  id: 147,
  title: "Young Justice – Season 2: Invasion (2012)",
  poster: "/a147id.jpg",
  trailer: "https://www.youtube.com/embed/SQi0Ll6vNpM?si",
  telegramLink: "https://t.me/animeversebd/2931",
  genre: "Animation | Action | Sci-Fi",
  year: "2012",
  rating: "8.9",
  language: "hindi",
  description: "সময়ের ব্যবধানের পর টিম ফিরে আসে নতুন সদস্য নিয়ে, যেখানে পৃথিবীকে আক্রমণ করতে চায় এক এলিয়েন শক্তি।",
  views: 1700
},
{
  id: 148,
  title: "Young Justice – Season 3: Outsiders (2019)",
  poster: "/a148id.jpg",
  trailer: "https://www.youtube.com/embed/SQi0Ll6vNpM?si",
  telegramLink: "https://t.me/animeversebd/2936",
  genre: "Animation | Sports | Shounen",
  year: "2019",
  rating: "8.5",
  language: "Hindi",
  description: "মেটা-ট্রাফিকিংকে থামাতে টিম নিয়ন্ত্রণের বাইরে থাকা এক অন্ধকার চক্রের বিরুদ্ধে লড়াইয়ে নামে।",
  views: 1700
},
{
  id: 149,
  title: "Bat-Fam – Season 1 (2024)",
  poster: "/a149id.jpg",
  trailer: "https://www.youtube.com/embed/_UM-Q9TZig0?si",
  telegramLink: "https://t.me/animeversebd/2940",
  genre: "Animation | Sports | Teamwork",
  year: "2024",
  rating: "9.1",
  language: "Hindi",
  description: "ব্যাটম্যানের পরিবার—নাইটউইং, রেড হুড, রবিন, ব্যাটগার্ল—সবাই মিলে হাস্যরস আর অ্যাকশনে ভরপুর এক পাগলাটে অ্যাডভেঞ্চারে জড়িয়ে পড়ে।",
  views: 1700
},
{
  id: 150,
  title: "Chainsaw Man – Season 1 (2022)",
  poster: "/a150id.jpg",
  trailer: "https://www.youtube.com/embed/nl9GzV4cltU?si",
  telegramLink: "https://t.me/animeversebd/2945",
  genre: "Animation | Comedy | Superhero",
  year: "2022",
  rating: "8.3",
  language: "Hindi",
  description: "দেরিদ্র ডেনজি তার পোষা ডেভিল পোচিতাকে নিয়ে ডেভিল হান্টার হয়, আর একদিন সে নিজেই হয়ে যায় মানব-ডেভিলের প্রাণঘাতী রূপ—চেইনসো ম্যান।",
  views: 1700
},
{
  id: 151,
  title: "Chainsaw Man: The Movie – Reze Arc (2025)",
  poster: "/a151id.jpg",
  trailer: "https://www.youtube.com/embed/nl9GzV4cltU?si",
  telegramLink: "https://t.me/animeversebd/2972",
  genre: "Animation | Comedy | Fantasy",
  year: "2025",
  rating: "8.7",
  language: "Hindi",
  description: "ডেনজির জীবনে আসে রহস্যময় মেয়ে Reze। প্রেম, প্রতারণা আর ধ্বংসের মাঝখানে সে পড়ে সবচেয়ে হৃদয়ভাঙা যুদ্ধের মুখোমুখি।",
  views: 1700
},
  {
    id: 152,
    title: "Naruto Shippuden – Season 15 (2012) complete☑️",
    poster: "/a152id.jpg",
    trailer: "https://www.youtube.com/embed/KpLFe8kYHVE?si",
    telegramLink: "https://t.me/animeversebd/2976",
    genre: "Animation | Comedy | Sci-Fi",
    year: "2025",
    rating: "8.6",
    language: "Hindi",
    description: "চতুর্থ মহা নিনজা যুদ্ধে নারুতো ও কিলার বি সামনের সারিতে লড়াই করে, যেখানে মুখোমুখি হতে হয় টেইলড বিস্ট ও আকাতসুকির অন্ধকার শক্তির।",
    views: 1700
  },
  {
    id: 153,
    title: "A Couple of Cuckoos (2025)",
    poster: "/a153id.jpg",
    trailer: "https://www.youtube.com/embed/4m9XEG4lMHQ?si",
    telegramLink: "https://t.me/animeversebd/3237",
    genre: "Comedy | Drama | Romance ",
    year: "2025",
    rating: "8.3",
    language: "Dual audio",
    description: "নিষিদ্ধ সম্পর্ক আর সামাজিক টানাপোড়েনে এক নারীর জীবনের কঠিন বাস্তবতা সামনে আসে।",
    views: 23847,
  },
  {
    id: 154,
    title: "Kaiju No. 8 (2024) Season 1",
    poster: "/a154id.jpg",
    trailer: "https://www.youtube.com/embed/_NihiaU1xR8?si",
    telegramLink: "https://t.me/animeversebd/3258",
    genre: "Action | Sci-Fi | Animation",
    year: "2024",
    rating: "8.3",
    language: "Japanese/Hindi",
    description: "কাফকা হিবিনো এমন এক পৃথিবীতে বাস করে যেখানে দানব বা 'কাইজু' সাধারণ ঘটনা। ছোটবেলার স্বপ্ন পূরণ করতে ডিফেন্স ফোর্সে যোগ দেওয়ার আগেই একটি ছোট কাইজু তার শরীরে ঢুকে পড়ে, যার ফলে সে নিজেও একটি শক্তিশালী কাইজুতে রূপান্তরিত হয়। এখন নিজের পরিচয় গোপন রেখে তাকে লড়তে হবে দানবদের বিরুদ্ধে এবং রক্ষা করতে হবে মানবজাতিকে।",
    views: 23847,
  },
  {
    id: 155,
    title: "Overflow – Season 1 (2020)",
    poster: "/a155id.jpg",
    trailer: "https://www.youtube.com/embed/i6L-1x6OR8A?si",
    telegramLink: "https://t.me/animeversebd/3278",
    genre: "Romance | Adult | Drama",
    year: "2020",
    rating: "6.1",
    language: "Japanese",
    description: "দৈনন্দিন জীবনের কাছাকাছি থাকা মানুষদের মাঝে সীমা ভাঙা সম্পর্ক ধীরে ধীরে জটিল আবেগের গল্পে রূপ নেয়।",
    views: 23847,
  },
  {
    id: 156,
    title: "Alya Sometimes Hides Her Feelings in Russian – Season 1 (2024)",
    poster: "/a156id.jpg",
    trailer: "https://www.youtube.com/embed/rl9Vkft_mp0?si",
    telegramLink: "https://t.me/animeversebd/3362",
    genre: "Romance | Comedy | Slice of Life",
    year: "2024",
    rating: "6.7",
    language: "Japanese/Hindi",
    description: "স্কুল জীবনের মাঝেই শুরু হয় এক মিষ্টি প্রেমকাহিনি, যেখানে আল্যা নিজের অনুভূতি রাশিয়ান ভাষায় লুকিয়ে প্রকাশ করে—যা অজান্তেই একজনই বুঝতে পারে।",
    views: 23847,
  },
  {
    id: 157,
    title: "Kaiju No. 8 (2025) Season 2",
    poster: "/a157id.jpg",
    trailer: "https://www.youtube.com/embed/b9jT7nQ3YUs?si",
    telegramLink: "https://t.me/animeversebd/3391",
    genre: "Action | Sci-Fi | Animation",
    year: "2025",
    rating: "7.8",
    language: "Japanese / Hindi",
    description: "ডিফেন্স ফোর্সে নিজের অবস্থান শক্ত করার পাশাপাশি কাফকা হিবিনো এখন আরও ভয়ংকর কাইজুদের মুখোমুখি হয়। তার কাইজু শক্তির রহস্য ধীরে ধীরে প্রকাশ পেতে শুরু করে, যা ডিফেন্স ফোর্স এবং মানবজাতির জন্য এক বড় হুমকি হয়ে দাঁড়ায়। নিজের পরিচয় গোপন রেখে বন্ধুদের রক্ষা করা এবং মানব বনাম কাইজুর যুদ্ধের সত্য উদঘাটন—এই নিয়েই এগিয়ে যায় সিজন ২-এর কাহিনি।",
    views: 23847,
  },
  {
    id: 158,
    title: "Campfire Cooking in Another World with My Absurd Skill (2023)",
    poster: "/a158id.jpg",
    trailer: "https://www.youtube.com/embed/a6vemmeN7NE?si",
    telegramLink: "https://t.me/animeversebd/3414",
    genre: "Fantasy | Adventure | Cooking | Slice of Life",
    year: "2023",
    rating: "7.4",
    language: "Japanese/Hindi",
    description: "এক সাধারণ মানুষ হঠাৎ অন্য জগতে召summon হলেও যুদ্ধের বদলে তার বিশেষ ক্ষমতা হয়ে ওঠে আধুনিক রান্না।",
    views: 23847,
  },
  {
    id: 159,
    title: "Tokyo Ghoul – Season 1 (2014)",
    poster: "/a159id.jpg",
    trailer: "https://www.youtube.com/embed/tLWEP0wgrsw?si",
    telegramLink: "https://t.me/animeversebd/3441",
    genre: "Fantasy | Horror | Action",
    year: "2025",
    rating: "7.7",
    language: "Hindi",
    description: "টোকিও শহরে মানুষের ভেতর লুকিয়ে থাকা গৌলদের জগতে হঠাৎ জড়িয়ে পড়ে সাধারণ কলেজ ছাত্র কানেকি। এক ভয়ংকর দুর্ঘটনার পর সে হয়ে ওঠে আধা-মানব, আধা-গৌল—যেখানে মানবিকতা আর দানবীয় প্রবৃত্তির মধ্যে শুরু হয় তার অস্তিত্বের লড়াই।",
    views: 23847,
  },
  {
    id: 160,
    title: "Luck (2022)",
    poster: "/a160id.jpg",
    trailer: "https://www.youtube.com/embed/xSG5UX0EQVg?si",
    telegramLink: "https://t.me/animeversebd/3456",
    genre: "Animation | Adventure | Comedy | Fantasy",
    year: "2022",
    rating: "6.4",
    language: "Hindi",
    description: "ভাগ্যহীন এক মেয়ের জীবন হঠাৎ বদলে যায় যখন সে আবিষ্কার করে ভাগ্য আর দুর্ভাগ্যের গোপন জগৎ। সৌভাগ্য আর দুর্ভাগ্যের শক্তির মাঝে আটকে গিয়ে, নিজের ভাগ্য বদলানোর পাশাপাশি সে শিখে নেয় জীবনের আসল মূল্য। 🍀✨",
    views: 23847,
  },
  {
    id: 161,
    title: "Jujutsu Kaisen – Season 1 (2020)",
    poster: "/a161id.jpg",
    trailer: "https://www.youtube.com/embed/JLthUWQCqZ8?si",
    telegramLink: "https://t.me/animeversebd/3458",
    genre: "Anime | Action | Fantasy | Supernatural",
    year: "2020",
    rating: "8.6",
    language: "Hindi",
    description: "অভিশপ্ত আত্মা আর জাদুবিদ্যার জগতে হঠাৎ জড়িয়ে পড়ে সাধারণ ছাত্র ইউজি ইতাদোরি। মানবতা বাঁচাতে তাকে শিখতে হয় জুজুৎসু জাদু, যেখানে প্রতিটি লড়াই মানেই জীবন-মৃত্যুর পরীক্ষা। ⚔️👹",
    views: 23847,
  },
  {
    id: 162,
    title: "Jujutsu Kaisen – Season 2 (2023)",
    poster: "/a162id.jpg",
    trailer: "https://www.youtube.com/embed/wUAgibbAW6w?si",
    telegramLink: "https://t.me/animeversebd/3510",
    genre: "Anime | Action | Dark Fantasy",
    year: "2023",
    rating: "9.0",
    language: "Hindi",
    description: "গোজো সাতোরুর অতীত, অভিশাপের ভয়ংকর উত্থান আর শিবুয়া ইনসিডেন্ট—সব মিলিয়ে আরও অন্ধকার ও আবেগঘন অধ্যায়। বিশ্বাসঘাতকতা, ত্যাগ আর ভয়াবহ যুদ্ধ সিরিজটাকে নিয়ে যায় এক নতুন উচ্চতায়। 🔥🌀",
    views: 23847,
  },
  {
    id: 163,
    title: "Doraemon – Season 1 (1989)",
    poster: "/a163id.jpg",
    trailer: "https://www.youtube.com/embed/wUAgibbAW6w?si",
    telegramLink: "https://t.me/animeversebd/3621",
    genre: "Animation | Comedy | Family | Sci-Fi",
    year: "2023",
    rating: "8.5",
    language: "Hindi org",
    description: "ভবিষ্যৎ থেকে আসা রোবট বিড়াল ডোরেমন আর অলস কিন্তু সৎ নোবিতার দৈনন্দিন মজার অ্যাডভেঞ্চার। অদ্ভুত গ্যাজেট, বন্ধুত্ব আর নৈতিক শিক্ষায় ভরা এক কালজয়ী সিরিজ। 🤖✨",
    views: 23847,
  },
  {
    id: 164,
    title: "Hotel Transylvania (2012)",
    poster: "/a164id.jpg",
    trailer: "https://www.youtube.com/embed/ZbWoqGky7qQ?si",
    telegramLink: "https://t.me/animeversebd/3733",
    genre: "Animation | Comedy | Family | Fantasy",
    year: "2012",
    rating: "7.0",
    language: "English/Hindi",
    description: "ড্রাকুলা তার মেয়ে মেভিসকে মানুষদের থেকে দূরে রাখতে তৈরি করে এক বিশেষ হোটেল, যেখানে সব দানবরা নিরাপদে থাকতে পারে। কিন্তু এক মানব যুবক ভুল করে সেখানে ঢুকে পড়লে শুরু হয় মজার ঝামেলা—আর বদলে যেতে থাকে ড্রাকুলার জীবনের নিয়মকানুন। 🧛‍♂️🏨",
    views: 23847,
  },
  {
    id: 165,
    title: "Doraemon: Nobita in the Robot Kingdom (2002)",
    poster: "/a165id.jpg",
    trailer: "https://www.youtube.com/embed/MdIooyfk8k4?si",
    telegramLink: "https://t.me/animeversebd/3735",
    genre: "Animation | Adventure | Family | Sci-Fi",
    year: "2002",
    rating: "7.1",
    language: "Japanese/Hindi",
    description: "ডোরেমন ও নোবিতা হঠাৎ করে চলে যায় এক রোবটদের রাজ্যে, যেখানে মানুষ ও রোবটের সম্পর্ক চরম সংকটে। বন্ধুত্ব ও সাহস নিয়ে তারা চেষ্টা করে অন্যায় শাসনের বিরুদ্ধে দাঁড়াতে, যাতে মানুষ ও রোবট আবার একসাথে শান্তিতে থাকতে পারে।",
    views: 23847,
  },
  {
    id: 166,
    title: "A Misanthrope Teaches a Class for Demi-Humans (2026)",
    poster: "/a166id.jpg",
    trailer: "https://www.youtube.com/embed/88ZTLBK9nKU?si",
    telegramLink: "https://t.me/animeversebd/3737",
    genre: "Anime | Fantasy | Drama",
    year: "2026",
    rating: "7.4",
    language: "Hindi",
    description: "মানুষ ও ডেমি-হিউম্যানদের মধ্যে অবিশ্বাসের দেয়াল ভাঙতে চায় এক নিঃসঙ্গ ও বিরক্ত শিক্ষক। শ্রেণিকক্ষের ভেতর দিয়ে ধীরে ধীরে জন্ম নেয় বোঝাপড়া, সহমর্মিতা আর বন্ধুত্বের নতুন গল্প। 🧑‍🏫✨",
    views: 23847,
  },
  {
    id: 167,
    title: "Isekai Onsen Paradise – Season 1 (2024) 1080P☑️",
    poster: "/a167id.jpg",
    trailer: "https://www.youtube.com/embed/3CbqnCaHXBg?si",
    telegramLink: "https://t.me/animeversebd/3741",
    genre: "Fantasy | Comedy | Isekai",
    year: "2024",
    rating: "6.9",
    language: "English",
    description: "এক ব্যক্তি হঠাৎ অন্য জগতে গিয়ে আবিষ্কার করে এক জাদুকরী অনসেন (হট স্প্রিং)। মজার পরিস্থিতি, নতুন বন্ধু আর অদ্ভুত অ্যাডভেঞ্চারে ভরা এক হালকা ফ্যান্টাসি যাত্রা। ♨️✨",
    views: 23847,
  },
]

export const animeGenres = [
  "Action",
  "Comedy",
  "Drama",
  "Adventure",
  "Supernatural",
  "Fantasy",
  "Sci-Fi",
  "Thriller",
  "Romance",
  "Historical",
  "School",
  "Martial Arts",
  "Adult",
]
